"""Platform boundary: effects stay behind a backend, policy stays in Jarvis."""
from typing import Protocol


class PlatformBackend(Protocol):
    name: str
    computer: object
    control_names: set
    desktop_os_names: set

    def tool_specs(self, desktop_specs): ...
    def resolve(self, text): ...
    def handles(self, name): ...
    def run(self, name, arguments, approved=None, session=None): ...
    def command(self, bot, command, argument): ...
